fotoservicio:
    path:     /
    defaults: { _controller: "feriaagropecuariaBackendBundle:FotoServicio:index" }

fotoservicio_show:
    path:     /{id}/show
    defaults: { _controller: "feriaagropecuariaBackendBundle:FotoServicio:show" }

fotoservicio_new:
    path:     /new
    defaults: { _controller: "feriaagropecuariaBackendBundle:FotoServicio:new" }

fotoservicio_create:
    path:     /create
    defaults: { _controller: "feriaagropecuariaBackendBundle:FotoServicio:create" }
    methods:  POST

fotoservicio_edit:
    path:     /{id}/edit
    defaults: { _controller: "feriaagropecuariaBackendBundle:FotoServicio:edit" }

fotoservicio_update:
    path:     /{id}/update
    defaults: { _controller: "feriaagropecuariaBackendBundle:FotoServicio:update" }
    methods:  [POST, PUT]

fotoservicio_delete:
    path:     /{id}/delete
    defaults: { _controller: "feriaagropecuariaBackendBundle:FotoServicio:delete" }
    methods:  [POST, DELETE]
