foto:
    path:     /
    defaults: { _controller: "feriaagropecuariaBackendBundle:Foto:index" }

foto_show:
    path:     /{id}/show
    defaults: { _controller: "feriaagropecuariaBackendBundle:Foto:show" }

foto_new:
    path:     /new
    defaults: { _controller: "feriaagropecuariaBackendBundle:Foto:new" }

foto_create:
    path:     /create
    defaults: { _controller: "feriaagropecuariaBackendBundle:Foto:create" }
    methods:  POST

foto_edit:
    path:     /{id}/edit
    defaults: { _controller: "feriaagropecuariaBackendBundle:Foto:edit" }

foto_update:
    path:     /{id}/update
    defaults: { _controller: "feriaagropecuariaBackendBundle:Foto:update" }
    methods:  [POST, PUT]

foto_delete:
    path:     /{id}/delete
    defaults: { _controller: "feriaagropecuariaBackendBundle:Foto:delete" }
    methods:  [POST, DELETE]
