producto:
    path:     /
    defaults: { _controller: "feriaagropecuariaBackendBundle:Producto:index" }

producto_show:
    path:     /{id}/show
    defaults: { _controller: "feriaagropecuariaBackendBundle:Producto:show" }

producto_new:
    path:     /new
    defaults: { _controller: "feriaagropecuariaBackendBundle:Producto:new" }

producto_create:
    path:     /create
    defaults: { _controller: "feriaagropecuariaBackendBundle:Producto:create" }
    methods:  POST

producto_edit:
    path:     /{id}/edit
    defaults: { _controller: "feriaagropecuariaBackendBundle:Producto:edit" }

producto_update:
    path:     /{id}/update
    defaults: { _controller: "feriaagropecuariaBackendBundle:Producto:update" }
    methods:  [POST, PUT]

producto_delete:
    path:     /{id}/delete
    defaults: { _controller: "feriaagropecuariaBackendBundle:Producto:delete" }
    methods:  [POST, DELETE]
