servicio:
    path:     /
    defaults: { _controller: "feriaagropecuariaBackendBundle:Servicio:index" }

servicio_show:
    path:     /{id}/show
    defaults: { _controller: "feriaagropecuariaBackendBundle:Servicio:show" }

servicio_new:
    path:     /new
    defaults: { _controller: "feriaagropecuariaBackendBundle:Servicio:new" }

servicio_create:
    path:     /create
    defaults: { _controller: "feriaagropecuariaBackendBundle:Servicio:create" }
    methods:  POST

servicio_edit:
    path:     /{id}/edit
    defaults: { _controller: "feriaagropecuariaBackendBundle:Servicio:edit" }

servicio_update:
    path:     /{id}/update
    defaults: { _controller: "feriaagropecuariaBackendBundle:Servicio:update" }
    methods:  [POST, PUT]

servicio_delete:
    path:     /{id}/delete
    defaults: { _controller: "feriaagropecuariaBackendBundle:Servicio:delete" }
    methods:  [POST, DELETE]
